import React from 'react';
import { Sparkles, FileText, Share2, Download, ExternalLink } from 'lucide-react';

const DashboardSummary = ({ disaster }) => {
  const generateSummary = () => {
    const { name, type, date, country, stats } = disaster;
    return `The ${name} (${type}) struck ${country} on ${date}, affecting approximately ${stats.area_affected} of territory. Initial satellite imagery analysis indicates ${stats.destroyed_pct}% of surveyed structures sustained catastrophic damage, with an additional ${stats.major_damage_pct}% showing significant structural compromise. Emergency response coordination is recommended for ${stats.structures_destroyed?.toLocaleString() || 'numerous'} confirmed destroyed buildings. Current humanitarian impact assessment estimates ${stats.casualties?.toLocaleString() || 'significant'} casualties. Economic damage projections place total losses at ${stats.economic_loss || 'substantial figures'}.`;
  };

  const bulletPoints = [
    `Primary impact zone: ${disaster.country}`,
    `Event classification: ${disaster.type}`,
    `Structural damage rate: ${(disaster.stats.major_damage_pct || 0) + (disaster.stats.destroyed_pct || 0)}%`,
    `Recommended response level: ${disaster.stats.destroyed_pct > 40 ? 'CRITICAL' : disaster.stats.destroyed_pct > 20 ? 'HIGH' : 'MODERATE'}`,
  ];

  return (
    <div className="bg-graphite rounded-3xl border border-gray-800 p-4 shadow-glow">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-plasma to-plasma/50 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 className="font-sora font-semibold text-ghost text-sm">AI Situation Summary</h3>
            <p className="text-xs font-mono text-gray-500">Generated by Terrascope AI</p>
          </div>
        </div>
        <span className="text-[9px] font-mono text-plasma/70 px-2 py-1 bg-plasma/5 rounded-full border border-plasma/10">
          AUTO-GENERATED
        </span>
      </div>

      {/* Summary Text */}
      <div className="bg-void rounded-2xl border border-gray-800 p-4 mb-4">
        <p className="text-sm text-gray-300 leading-relaxed font-light">
          {generateSummary()}
        </p>
      </div>

      {/* Key Points */}
      <div className="space-y-2 mb-4">
        <div className="text-[10px] font-mono text-gray-500 uppercase tracking-wider">Key Findings</div>
        {bulletPoints.map((point, idx) => (
          <div key={idx} className="flex items-start gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-plasma mt-1.5 flex-shrink-0" />
            <span className="text-xs text-gray-400">{point}</span>
          </div>
        ))}
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-2 pt-4 border-t border-gray-800">
        <button className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-void border border-gray-700 text-xs text-gray-400 hover:text-ghost hover:border-plasma/50 transition-all">
          <FileText className="w-3.5 h-3.5" />
          Full Report
        </button>
        <button className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-void border border-gray-700 text-xs text-gray-400 hover:text-ghost hover:border-plasma/50 transition-all">
          <Download className="w-3.5 h-3.5" />
          Export PDF
        </button>
        <button className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-void border border-gray-700 text-xs text-gray-400 hover:text-ghost hover:border-plasma/50 transition-all">
          <Share2 className="w-3.5 h-3.5" />
          Share
        </button>
        <button className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-plasma/10 border border-plasma/30 text-xs text-plasma hover:bg-plasma/20 transition-all ml-auto">
          <ExternalLink className="w-3.5 h-3.5" />
          View Source Data
        </button>
      </div>

      {/* Timestamp */}
      <div className="mt-4 pt-3 border-t border-gray-800/50 flex items-center justify-between">
        <span className="text-[9px] font-mono text-gray-600">
          Analysis based on historical satellite data and verified reports
        </span>
        <span className="text-[9px] font-mono text-gray-600">
          Model: Terrascope v2.1
        </span>
      </div>
    </div>
  );
};

export default DashboardSummary;
